name: Add New Speaker

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-speaker:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process Issue and Update Speakers
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: node ci/add-speaker.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add new speaker: ${{ github.event.issue.title }}"
          title: "Add new speaker: ${{ github.event.issue.title }}"
          body: |
            Adds new speaker from issue #${{ github.event.issue.number }}
            
            This PR was automatically created by the Add Speaker workflow.
          branch: add-speaker-${{ github.event.issue.number }}
          delete-branch: true
          labels: |
            automated-pr
            speaker-addition

      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: '✅ A Pull Request has been created to add this speaker to speakers.json'
            }); 
